### PR TITLE
Optimize rendering

### LINKED ISSUE #140: Make raster work
Title says it all

### LINKED ISSUE #307: BUG: Coverage report missing
After our transition to Cython, pytest coverage reports are no longer accurate because they are being based on the C code. We need to somehow find a way to get coverage reports for compiled Cython code

### LINKED ISSUE #311: Optimize Rendering
Fix images to be good and use the pysdl pixelaccess for rasters

Helps with #301 #306 and #140

### PR DESCRIPTION
**Pull request by tinmarr**
Rendering system overhaul

Closes #311
Closes #140 
Closes #307 

## Still To Do

- [x] move fill logic into C for all shapes needing it
- [x] different shapes to physics demo
- [x] update changelog
- [x] update pixel mutation tutorial

## Hello reviewers!
Before approving this PR, please ensure the following:

  - [x] Documentation is up to date
  - [x] Relevent tutorials are up to date
  - [x] Changelog is up to date
  - [x] Test coverage is at 100%
  - [x] All checks are passing
  - [x] That the new code actually works

Once all this is done, you can be sure that the PR is ready to be merged. 🎉

*This message has been added automatically. Please don't delete it.*

### CODE REVIEW

**Comment by tinmarr** [comment]
Still TODO:

- [ ] Thick shapes
- [ ] Filled polygon

**Comment by tinmarr** [comment]
filled polygon aa algo: 
https://diglib.eg.org/bitstream/handle/10.2312/LocalChapterEvents.TPCG.TPCG07.081-088/081-088.pdf?sequence=1

**Comment by tsedan** [comment]
todo:

1. move fill logic into C for all shapes needing it
2. different shapes to physics demo
3. update changelog
4. update pixel mutation tutorial

**Review by tsedan — APPROVED** [review]
gog

**Pull request merged**
